# Generated by Django 5.0.7 on 2024-07-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddata',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
